language: ruby
rvm:
- 1.9.3
- 2.0.0
- 2.1.0
- rbx
- jruby
#deploy:
#  on:
#    all_branches: true
env:
  global:
    secure: T8L84sWENsNlck2SGTUOmB1OKsJRiam0jsUIXi0QhGlAPSP92h1WvpohixBtbp8FpaPqsG9YSwKj20VzauqwnEWkbtv0Yu9tfjJwWIvlZwdJHRp1KBRs4HeOlOiX6HEv1a0ahBp0pOK3jLojoDfxiqHU8H7B4GhKw0f5G0vkUvc=


after_success:
- coveralls
- [ integration = "stable" ] && git push https://${GITHUB_TOKEN}:x-oauth-basic@github.com/${TRAVIS_REPO_SLUG}.git HEAD:master

